version: "3"
services:
  server:
    container_name: server
    user: root
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - "./app:/app"
    # depends_on:
    #   - php
  
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./dockerfiles/php-fpm.dockerfile
    volumes:
      - "./app:/app"
