version: "3"
services:
  server:
    container_name: server
    user: root
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - "./app:/app"
    # depends_on:
    #   - php
  
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - "./app:/app"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
  
  mongo:
    container_name: mongo
    image: mongo:3.6.21-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    volumes:
      - database:/data/db

volumes:
  database: